### PR TITLE
Added an input box for easy background usage.

### PR DESCRIPTION
**Pull request by NanoAi**
Added an input box for easy background usage.

Screenshot: http://i.imgur.com/JxefHyq.png
Mirror: http://i.snag.gy/xmMPD.jpg

### CODE REVIEW

**Comment by TrueCarry** [comment]
But there is another input on top of the page?

**Comment by NanoAi** [comment]
I was not seeing it. I managed to get it to come up after some tinkering.
But it was not working properly at all. Besides with my addition people can
use any image not just steam images.

**Comment by TrueCarry** [comment]
I just checked with http://i.imgur.com/mYuQ8oU.jpg.  It works. But if you don't see this input, it means we need to change something. Can you add me on steam, I have idea to discuss.

**Comment by NanoAi** [comment]
Yeah, I am steamcommunity.com/id/boopyouredead

Add me and I will add you back.

**Pull request closed without merging**
